/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DmgBackBtn {
    }
    interface DmgButton {
    }
}
declare global {
    interface HTMLDmgBackBtnElement extends Components.DmgBackBtn, HTMLStencilElement {
    }
    var HTMLDmgBackBtnElement: {
        prototype: HTMLDmgBackBtnElement;
        new (): HTMLDmgBackBtnElement;
    };
    interface HTMLDmgButtonElement extends Components.DmgButton, HTMLStencilElement {
    }
    var HTMLDmgButtonElement: {
        prototype: HTMLDmgButtonElement;
        new (): HTMLDmgButtonElement;
    };
    interface HTMLElementTagNameMap {
        "dmg-back-btn": HTMLDmgBackBtnElement;
        "dmg-button": HTMLDmgButtonElement;
    }
}
declare namespace LocalJSX {
    interface DmgBackBtn {
    }
    interface DmgButton {
    }
    interface IntrinsicElements {
        "dmg-back-btn": DmgBackBtn;
        "dmg-button": DmgButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dmg-back-btn": LocalJSX.DmgBackBtn & JSXBase.HTMLAttributes<HTMLDmgBackBtnElement>;
            "dmg-button": LocalJSX.DmgButton & JSXBase.HTMLAttributes<HTMLDmgButtonElement>;
        }
    }
}
